[package]

name = "error"
version = "0.0.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[lib]

name = "error"
path = "src/lib.rs"

[dependencies.typeable]

git = "https://github.com/reem/rust-typeable.git"

